In [1]:
 %matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns
    

In [2]:
import antipackage
from github.ellisonbg.misc import vizarray as va


Downloading:  https://raw.githubusercontent.com/ellisonbg/misc/master/vizarray.py
Using existing version:  github.ellisonbg.misc.vizarray


In [3]:
import numpy as np

In [4]:
data = [0,2,4,6]
a = np.array(data)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array([0, 2, 4, 6])

In [7]:
va.vizarray(a)

In [8]:
a.shape

(4,)

In [9]:
a.ndim

1

In [10]:
a.size

4

In [11]:
a.nbytes

32

In [12]:
a.dtype

dtype('int64')

In [14]:
data = [[0.0,2.0,4.0,6.0],[1.0,3.0,5.0,7.0]]
b=np.array(data)

In [15]:
b

array([[ 0.,  2.,  4.,  6.],
       [ 1.,  3.,  5.,  7.]])

In [16]:
va.vizarray(b)


In [17]:
b.shape, b.ndim, b.size, b.nbytes


((2, 4), 2, 8, 64)

In [18]:
c = np.arange(0.0,10.0,1.0)
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [20]:
e = np.linspace(0.0,5.0,11)
e


array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [21]:
np.empty((4,4))

array([[  6.92349845e-310,   2.52948093e-316,   6.92349866e-310,
          6.92346016e-310],
       [  6.92349861e-310,   6.92346016e-310,   6.92349866e-310,
          6.92346016e-310],
       [  6.92349861e-310,   6.92346016e-310,   6.92349866e-310,
          6.92346016e-310],
       [  6.92349861e-310,   6.92346015e-310,   6.92349866e-310,
          6.92346016e-310]])

In [22]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
np.ones((3,3
))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
a = np.array([0,1,2,3])

In [26]:
a, a.dtype

(array([0, 1, 2, 3]), dtype('int64'))

In [29]:
b = np.zeros((2,2), dtype=np.complex64)
b

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]], dtype=complex64)

In [30]:
c = np.arange(0,10,2,dtype=np.float)
c

array([ 0.,  2.,  4.,  6.,  8.])

In [31]:
d=c.astype(dtype=np.int)
d

array([0, 2, 4, 6, 8])

In [32]:
np.float*?

In [35]:
a = np.empty((3,3))
a.fill(0.1)
a

array([[ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1]])

In [36]:
b = np.ones((3,3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [34]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

In [37]:
b/a

array([[ 10.,  10.,  10.],
       [ 10.,  10.,  10.],
       [ 10.,  10.,  10.]])

In [38]:
a**2

array([[ 0.01,  0.01,  0.01],
       [ 0.01,  0.01,  0.01],
       [ 0.01,  0.01,  0.01]])

In [39]:
np.pi*b

array([[ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265]])

In [45]:
a= np.random.rand(10,10)

In [46]:
va.enable()

In [47]:
a

array([[ 0.33947943,  0.6536712 ,  0.64863989,  0.7248363 ,  0.72405591,
         0.32085923,  0.05402576,  0.38772007,  0.93522637,  0.23308713],
       [ 0.33445713,  0.24873815,  0.63522474,  0.10828664,  0.45593961,
         0.76705515,  0.01808006,  0.67257967,  0.19705208,  0.82534665],
       [ 0.16598766,  0.2985038 ,  0.84130965,  0.61236842,  0.73052472,
         0.20830612,  0.69821222,  0.04413379,  0.66049421,  0.58535731],
       [ 0.82816661,  0.80545027,  0.38084977,  0.76333389,  0.3062349 ,
         0.72135677,  0.31996726,  0.33176656,  0.63785575,  0.56801352],
       [ 0.21387026,  0.79707683,  0.64469929,  0.51724101,  0.01861065,
         0.59132123,  0.38744417,  0.1633316 ,  0.28296916,  0.2944061 ],
       [ 0.32023951,  0.54345394,  0.96292121,  0.80149015,  0.78360248,
         0.89950424,  0.69275465,  0.85739063,  0.25328232,  0.44448311],
       [ 0.18124193,  0.06786286,  0.70400325,  0.67720235,  0.69928573,
         0.4691521 ,  0.40011844,  0.36114966,  0.29241507,  0.22743909],
       [ 0.93580057,  0.54294679,  0.72894813,  0.25083869,  0.78874466,
         0.03901797,  0.92642389,  0.73858335,  0.4565364 ,  0.23973792],
       [ 0.50490075,  0.66519028,  0.24229053,  0.926493  ,  0.84359569,
         0.69904625,  0.92940011,  0.25326881,  0.95191595,  0.2048659 ],
       [ 0.92303391,  0.99449744,  0.19031779,  0.8839335 ,  0.35455537,
         0.33721859,  0.73268641,  0.90759924,  0.06548939,  0.3937627 ]])